/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.appointmentregistration.view;

/**
 *
 * @author Roxana
 */
public class GUIAddAppointment extends javax.swing.JPanel {

    /**
     * Creates new form GUIADDAPPOINTMENT
     */
    public GUIAddAppointment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCalendar = new javax.swing.JTable();
        cbAreas = new javax.swing.JComboBox<>();
        btnExit = new javax.swing.JButton();
        cbAppointmentDate = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCalendar.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        tblCalendar.setForeground(new java.awt.Color(255, 255, 255));
        tblCalendar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ));
        jScrollPane1.setViewportView(tblCalendar);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 380, 240));

        cbAreas.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        cbAreas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbAreas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 152, 31));

        btnExit.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        btnExit.setText("Exit");
        add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 96, 34));

        cbAppointmentDate.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        cbAppointmentDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbAppointmentDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAppointmentDateActionPerformed(evt);
            }
        });
        add(cbAppointmentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 152, 30));

        jLabel2.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel2.setText("Area:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel3.setText("Appointment");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 620, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void cbAppointmentDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAppointmentDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAppointmentDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox<String> cbAppointmentDate;
    private javax.swing.JComboBox<String> cbAreas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCalendar;
    // End of variables declaration//GEN-END:variables
}
