/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.appointmentregistration.view;

/**
 *
 * @author Camila PB
 */
public class GUIBillIndication extends javax.swing.JFrame {

    /**
     * Creates new form GUIBillIndication
     */
    public GUIBillIndication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnelBill1 = new ucr.ac.cr.appointmentregistration.view.PnelBill();
        panelIndicationDoctor1 = new ucr.ac.cr.appointmentregistration.view.PanelIndicationDoctor();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnelBill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 400));
        getContentPane().add(panelIndicationDoctor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fon2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 460));

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 10, 520, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private ucr.ac.cr.appointmentregistration.view.PanelIndicationDoctor panelIndicationDoctor1;
    private ucr.ac.cr.appointmentregistration.view.PnelBill pnelBill1;
    // End of variables declaration//GEN-END:variables
}
