/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.ActionListener;

/**
 *
 * @author Usuario
 */
public class GUIMedicalMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MedicalMainMenu
     */
    public GUIMedicalMainMenu() {
        initComponents();
    }
    
    public void listenButton(ActionListener controller){
        this.btnRegistrationMedical.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrationMedical = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrationMedical.setBackground(new java.awt.Color(153, 153, 153));
        btnRegistrationMedical.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnRegistrationMedical.setForeground(new java.awt.Color(102, 102, 102));
        btnRegistrationMedical.setText("Registrar Citas");
        btnRegistrationMedical.setActionCommand("RegistrarCitas");
        btnRegistrationMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrationMedicalActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrationMedical, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 170, 60));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("SISTEMA DE REPORTE DE CITAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 240, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo5.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 340));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blanco.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 450, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrationMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrationMedicalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrationMedicalActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrationMedical;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
