/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.appointmentregistration.view;

/**
 *
 * @author Roxana
 */
public class GUIMedicalAppointment extends javax.swing.JPanel {

    /**
     * Creates new form GUIMedicalAppointment
     */
    public GUIMedicalAppointment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAppointment = new javax.swing.JButton();
        btnPatient = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAppointment.setFont(new java.awt.Font("Calisto MT", 3, 14)); // NOI18N
        btnAppointment.setText("APPOINTMENT");
        add(btnAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, 46));

        btnPatient.setFont(new java.awt.Font("Calisto MT", 3, 14)); // NOI18N
        btnPatient.setText("PATIENT DATA");
        add(btnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 180, 46));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 280));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nombre.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 360, 280));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointment;
    private javax.swing.JButton btnPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
