/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.appointmentregistration.view;

import java.awt.event.ActionListener;
import ucr.ac.cr.appointmentregistration.model.User;

/**
 *
 * @author Camila PB
 */
public class GUIRegisterUser extends javax.swing.JFrame {

    /**
     * Creates new form GUIRegisterUser
     */
    public GUIRegisterUser() {
        initComponents();
    }
    
    public User getUser(){
        return new User(Integer.parseInt(txtIdentificationCard.getText()),PFPassword.getText());
    
    }
    
    //Metodo que escucha los botones
    public void Listen(ActionListener controller){
        this.btAdd.addActionListener(controller);
        this.btClose.addActionListener(controller);
    }
    
    //Metodo para limpiar
    public void clean(){//Limpiar 
        this.txtIdentificationCard.setText("");
        this.PFPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdentificationCard = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        btClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PFPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel1.setText("Identification Card:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 57, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 115, 119, -1));

        txtIdentificationCard.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jPanel1.add(txtIdentificationCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 52, 213, -1));

        btAdd.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        btAdd.setText("Add");
        jPanel1.add(btAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 182, -1, -1));

        btClose.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        btClose.setText("Close");
        jPanel1.add(btClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 182, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Register User");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 405, -1));

        PFPassword.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jPanel1.add(PFPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 110, 213, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nombre3.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 3, 400, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PFPassword;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtIdentificationCard;
    // End of variables declaration//GEN-END:variables
}
