/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.appointmentregistration.view;

/**
 *
 * @author Camila PB
 */
public class GUIReport extends javax.swing.JFrame {

    /**
     * Creates new form GUIReport
     */
    public GUIReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnelBill1 = new ucr.ac.cr.appointmentregistration.view.PnelBill();
        panelIndicationDoctor1 = new ucr.ac.cr.appointmentregistration.view.PanelIndicationDoctor();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnelBill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 400));
        getContentPane().add(panelIndicationDoctor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 200, -1));

        jLabel1.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel1.setText("Report");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private ucr.ac.cr.appointmentregistration.view.PanelIndicationDoctor panelIndicationDoctor1;
    private ucr.ac.cr.appointmentregistration.view.PnelBill pnelBill1;
    // End of variables declaration//GEN-END:variables
}
