/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.appointmentregistration.view;

import java.awt.event.ActionListener;
/**
 *
 * @author Camila PB
 */
public class GUIUser extends javax.swing.JFrame {
    /**
     * Creates new form GUIUser 
     */
    public GUIUser() {
        initComponents();
    }
    
    //devuelve el numero de indentificacion
    public int getIdentificationCard(){
        if(txtIdentificationCard.getText().equalsIgnoreCase("")){
            return -1;
        }else{
           return Integer.parseInt(txtIdentificationCard.getText());
        }
    
    }
    
    public void clean(){//Limpiar 
        this.txtIdentificationCard.setText("");
        this.PSPassword.setText("");
    }
    
    //Metodo que escucha los botones
    public void Listen(ActionListener controller){
        this.btLogIn.addActionListener(controller);
        this.btSignUp.addActionListener(controller);
        this.btExit.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdentificationCard = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btLogIn = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        btSignUp = new javax.swing.JButton();
        PSPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel1.setText("Identification card:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 227, -1));

        jLabel2.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        txtIdentificationCard.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jPanel1.add(txtIdentificationCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 210, -1));

        jLabel3.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("User");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 19, 370, -1));

        btLogIn.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        btLogIn.setText("Log in");
        btLogIn.setActionCommand("LogIn");
        jPanel1.add(btLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        btExit.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        btExit.setText("Exit");
        jPanel1.add(btExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        btSignUp.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        btSignUp.setText("Sign up");
        btSignUp.setActionCommand("SignUp");
        jPanel1.add(btSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        PSPassword.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jPanel1.add(PSPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 120, 210, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nombre6.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 280));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PSPassword;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btLogIn;
    private javax.swing.JButton btSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtIdentificationCard;
    // End of variables declaration//GEN-END:variables
}
