/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.appointmentregistration.view;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class PanelMedicines extends javax.swing.JPanel {

    /**
     * Creates new form GUIMedicines
     */
    public PanelMedicines() {
        initComponents();
    }
    
    public void setDataTable(String[][] matrizDates,String[] titles){
        DefaultTableModel model= new DefaultTableModel(matrizDates,titles);
        tbMedicines.setModel(model);
           jScrollPane2.setViewportView(tbMedicines);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMedicines = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Medicines");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        tbMedicines.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        tbMedicines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbMedicines);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 370, 200));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fon2.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 280));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbMedicines;
    // End of variables declaration//GEN-END:variables
}
